version: 1.2
workflows:
  - subclass: WDL
    name: align_rna_sample
    readMePath: /workflows/align_rna_sample/README.md
    primaryDescriptorPath: /workflows/align_rna_sample/align_rna_sample.wdl
    testParameterFiles:
      - /workflows/align_rna_sample/align_rna_sample.json
    filters:
      branches:
        - main
        - develop
    publish: True
  - subclass: WDL
    name: call_sr_rna_fusions
    readMePath: /workflows/call_sr_rna_fusions/README.md
    primaryDescriptorPath: /workflows/call_sr_rna_fusions/call_sr_rna_fusions.wdl
    testParameterFiles:
      - /workflows/call_sr_rna_fusions/call_sr_rna_fusions.json
    filters:
      branches:
        - main
        - develop
    publish: True
  - subclass: WDL
    name: quantify_sr_rna
    readMePath: /workflows/quantify_sr_rna/README.md
    primaryDescriptorPath: /workflows/quantify_sr_rna/quantify_sr_rna.wdl
    testParameterFiles:
      - /workflows/quantify_sr_rna/quantify_sr_rna.json
    filters:
      branches:
        - main
        - develop
    publish: True
  - subclass: WDL
    name: process_sr_rna
    readMePath: /workflows/process_sr_rna/README.md
    primaryDescriptorPath: /workflows/process_sr_rna/process_sr_rna.wdl
    testParameterFiles:
      - /workflows/process_sr_rna/process_sr_rna.json
    filters:
      branches:
        - main
        - develop
    publish: True
